"""Walk-forward analysis -- the antidote to curve-fitting.

We slice the history into consecutive folds. On each *in-sample* window we
pick the parameter set with the best expectancy; we then trade those frozen
params on the *next, unseen* out-of-sample window. Concatenating all the
out-of-sample trades gives an honest estimate of live performance, because
every trade was generated by parameters chosen without seeing that data.

A strategy whose stitched-together OOS curve still has a positive
expectancy is far more trustworthy than one that only looks good on a
single optimized backtest.
"""
from __future__ import annotations

import itertools
from typing import Callable

import numpy as np
import pandas as pd

from . import backtest as B
from . import metrics as M


def _grid(param_grid: dict):
    keys = list(param_grid)
    for combo in itertools.product(*param_grid.values()):
        yield dict(zip(keys, combo))


def walk_forward(
    price: pd.DataFrame,
    strategy: Callable,
    param_grid: dict,
    cfg: B.BacktestConfig | None = None,
    n_folds: int = 5,
    train_frac: float = 0.6,
    objective: str = "expectancy_R",
    min_trades: int = 15,
):
    """Return (oos_trades, oos_equity, oos_stats, fold_log)."""
    cfg = cfg or B.BacktestConfig()
    n = len(price)
    fold_size = n // n_folds
    oos_trades = []
    fold_log = []
    equity = cfg.start_equity

    for f in range(n_folds):
        start = f * fold_size
        end = n if f == n_folds - 1 else (f + 1) * fold_size
        block = price.iloc[start:end]
        split = int(len(block) * train_frac)
        if split < 30 or len(block) - split < 10:
            continue
        train, test = block.iloc[:split], block.iloc[split:]

        # ---- optimize on the in-sample block ----
        best, best_score = None, -np.inf
        for params in _grid(param_grid):
            sig = strategy(train, **params)
            tr, eq = B.run(train, sig, cfg)
            if len(tr) < min_trades:
                continue
            st = M.compute(tr, eq, cfg.start_equity).as_dict()
            score = st[objective]
            if score > best_score:
                best_score, best = score, params
        if best is None:
            continue

        # ---- trade frozen params on the out-of-sample block ----
        test_cfg = B.BacktestConfig(
            start_equity=equity, risk_pct=cfg.risk_pct,
            max_contracts=cfg.max_contracts, intraday=cfg.intraday,
            costs=cfg.costs, allow_short=cfg.allow_short,
        )
        sig = strategy(test, **best)
        tr, eq = B.run(test, sig, test_cfg)
        if len(tr):
            equity = eq.iloc[-1]
            oos_trades.append(tr)
        fold_log.append({
            "fold": f, "train_n": len(train), "test_n": len(test),
            "params": best, "is_score": round(best_score, 3),
            "oos_trades": len(tr),
            "oos_expectancy_R": round(M.compute(tr, eq, test_cfg.start_equity).expectancy_R, 3) if len(tr) else None,
        })

    if not oos_trades:
        return pd.DataFrame(), pd.Series(dtype=float), M.compute(None, pd.Series(dtype=float), cfg.start_equity), fold_log

    all_tr = pd.concat(oos_trades, ignore_index=True)
    # rebuild a continuous OOS equity curve
    eq_vals, eq_idx, run_eq = [], [], cfg.start_equity
    for _, row in all_tr.iterrows():
        run_eq += row["pnl"]
        eq_vals.append(run_eq)
        eq_idx.append(row["exit_time"])
    oos_equity = pd.Series(eq_vals, index=pd.DatetimeIndex(eq_idx))
    stats = M.compute(all_tr, oos_equity, cfg.start_equity)
    return all_tr, oos_equity, stats, fold_log
